# Generated by Django 5.2.1 on 2025-05-29 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='dadosensor',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='ni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='sig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosensor',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dadosensor',
            name='contador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadosensor',
            name='luminosidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadosensor',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadosensor',
            name='umidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador')], max_length=20),
        ),
    ]
