# Generated by Django 5.2.1 on 2025-05-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_city', '0002_rename_nome_ambiente_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_city.ambiente'),
        ),
    ]
