# Generated by Django 5.2.1 on 2025-06-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_city', '0003_alter_sensor_ambiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='app_city.sensor')),
            ],
        ),
    ]
